### ISSUE TITLE
Under which license is this project?

### ISSUE THREAD

**Issue by Perflyst** [BaronKiko/LauncherHijack#25]
I don't see any license on this project. The repo you forked does not have one either but you did a lot modifications so I think it is time to add an open source license.

**Comment by BaronKiko** [comment]
The licence is in the readme, it's not technical or anything but it covers enough and it's inherited from the original project owner so I'm morally obliged to keep it.
I will leave this open as it belongs in its own licence file which can be done easily for next release

**Comment by Perflyst** [comment]
This is not a clear license. I would ask you to take a look at MIT license.
https://choosealicense.com/licenses/mit/

**Comment by BaronKiko** [comment]
Sure, will have a look when I'm updating it.

**Comment by basxto** [comment]
MIT and Apache don’t require to open source derivative work, GPL does.

> including a link to this repo. You have to send us a link to the modified version if it is ever public.

That is something you would need to add to all of them. I don’t know how that work, though.

If you want people to send you links, you should should provide an e-mail address or something.
Technically those 22 people, who forked your project on github, needed to send you and parrotgeek1 a link to their fork.

It’s also not allowed to add your app to https://apt.izzysoft.de/fdroid/index/info, since it redistributes binary apps and links to the repos.
Adding the app to f-droid would make it mandatory to change the code, release it, link to your repo and send you a link to it.
If there were a fork of a fork of a fork of a fork in future, a new fork would need to send a link to all 5 of them and also link to all 5 of them.
Forks can’t change the license and the way your license is writte, the code can only be hosted on github, since each fork needs to publish apks via github releases.

**Comment by BaronKiko** [comment]
This has been resolved on the firetv branch (current dev) and will be moved to main very soon. The project is now using GPL3
