### ISSUE TITLE
adb shell settings command within firestick

### ISSUE THREAD

**Issue by tuppaacc** [BaronKiko/LauncherHijack#38]
How do I run this exact “adb shell” commands in a terminal emulator locally on the firestick:

adb shell settings put secure enabled_accessibility_services com.baronkiko.launcherhijack/com.baronkiko.launcherhijack.AccServ

I just NEED THE COMMAND  and not how to run terminal emulator I already got that part working however when I run that command it doesn't work, I wanna be able to run it without a computer so Im using the app called remote adb shell from my phone

**Comment by BaronKiko** [comment]
You just can't get the perms to do it locally. I would have got the app to do it for you if you could.
You have to use a pc.

**Comment by tuppaacc** [comment]
> 
> 
> You just can't get the perms to do it locally. I would have got the app to do it for you if you could.
> You have to use a pc.

I not trying to do it locally (per se)

Shouldn't you be able to run the command if you are running it from your phone?
"Mouse toggle for firestick" does something like that without the need of a computer or adb, im just trying to achieve something similar with an app called  "remote adb shell" (aka terminal emulator) all I need is the actual command. Thanks!

**Comment by BaronKiko** [comment]
Doing it on your firestick is doing it locally.
ADB shell oppens up a terminal to you device from the desktop. If you use your app you don't need to open a shell because the app does it for you so you just need to run the other commands.
But you are limited with what you are allowed to do on fire divices. So you don't have perms to run accessibility changes locally. And so it's not going to work. Some things are possible but not everything 
Just plug it into a pc and do it from there. You would have done it in 20 mins rather than spending days on the issue.

**Comment by Hunter9888x** [comment]
start launcher hijack
Accessibility service through tasker app

Launcherhijack Tasker Task Backup
https://mega.nz/#!iaxFWAgb!WvmdfsW6rVwuRrpdOAs5q4BlZIXHAP49Xg0VxrkmsVk
Tasker
https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm
ADB Shell Command Tasker Plugin
https://play.google.com/store/apps/details?id=com.ADBPlugin
